import { db } from "@/db/prisma-client";
import { ProjectType } from "@/schemas/project";

const sample_data: ProjectType[] = [
  {
    id: "project_1",
    title: "Eco-Friendly Home Design",
    slides: null,
    user_id: "user_id_1",
    outlines: ["Introduction", "Materials", "Design Process", "Final Product"],
    is_deleted: false,
    is_sellable: true,
    variant_id: "variant_1",
    thumbnail: "/images/test/project_thumbnail_1.jpg",
    theme_name: "light",
    created_at: new Date("2024-10-01T10:00:00Z"),
    updated_at: new Date("2024-10-01T10:00:00Z"),
  },
  {
    id: "project_2",
    title: "AI-Powered Chatbot",
    slides: { slide1: "Introduction", slide2: "Features", slide3: "Demo" },
    user_id: "user_id_1",
    outlines: ["Overview", "Technology Stack", "Implementation", "Testing"],
    is_deleted: false,
    is_sellable: false,
    variant_id: null,
    thumbnail: "/images/test/project_thumbnail_1.jpg",
    theme_name: "dark",
    created_at: new Date("2024-10-02T11:00:00Z"),
    updated_at: new Date("2024-10-02T11:00:00Z"),
  },
  {
    id: "project_3",
    title: "Sustainable Fashion Guide",
    slides: null,
    user_id: "user_id_1",
    outlines: ["Introduction", "Materials", "Brands", "Conclusion"],
    is_deleted: false,
    is_sellable: true,
    variant_id: "variant_2",
    thumbnail: "/images/test/project_thumbnail_1.jpg",
    theme_name: "light",
    created_at: new Date("2024-10-03T12:00:00Z"),
    updated_at: new Date("2024-10-03T12:00:00Z"),
  },
  {
    id: "project_4",
    title: "Mobile App for Fitness",
    slides: {
      slide1: "Home Screen",
      slide2: "Workout Plans",
      slide3: "Progress Tracking",
    },
    user_id: "user_id_1",
    outlines: ["Concept", "Design", "Development", "Launch"],
    is_deleted: false,
    is_sellable: true,
    variant_id: "variant_3",
    thumbnail: "/images/test/project_thumbnail_1.jpg",
    theme_name: "dark",
    created_at: new Date("2024-10-04T13:00:00Z"),
    updated_at: new Date("2024-10-04T13:00:00Z"),
  },
  {
    id: "project_5",
    title: "Urban Gardening Handbook",
    slides: null,
    user_id: "user_id_1",
    outlines: ["Introduction", "Tools", "Techniques", "Case Studies"],
    is_deleted: false,
    is_sellable: false,
    variant_id: null,
    thumbnail: "/images/test/project_thumbnail_1.jpg",
    theme_name: "light",
    created_at: new Date("2024-10-05T14:00:00Z"),
    updated_at: new Date("2024-10-05T14:00:00Z"),
  },
  {
    id: "project_6",
    title: "Blockchain for Beginners",
    slides: {
      slide1: "What is Blockchain?",
      slide2: "Use Cases",
      slide3: "Future Trends",
    },
    user_id: "user_id_1",
    outlines: ["Basics", "Applications", "Challenges", "Conclusion"],
    is_deleted: false,
    is_sellable: true,
    variant_id: "variant_4",
    thumbnail: "/images/test/project_thumbnail_1.jpg",
    theme_name: "dark",
    created_at: new Date("2024-10-06T15:00:00Z"),
    updated_at: new Date("2024-10-06T15:00:00Z"),
  },
  {
    id: "project_7",
    title: "Minimalist Living Guide",
    slides: null,
    user_id: "user_id_1",
    outlines: ["Philosophy", "Decluttering", "Lifestyle Changes", "Benefits"],
    is_deleted: false,
    is_sellable: true,
    variant_id: "variant_5",
    thumbnail: "/images/test/project_thumbnail_1.jpg",
    theme_name: "light",
    created_at: new Date("2024-10-07T16:00:00Z"),
    updated_at: new Date("2024-10-07T16:00:00Z"),
  },
  {
    id: "project_8",
    title: "Virtual Reality in Education",
    slides: {
      slide1: "Introduction",
      slide2: "Applications",
      slide3: "Challenges",
    },
    user_id: "user_id_1",
    outlines: ["Overview", "Case Studies", "Future Prospects"],
    is_deleted: false,
    is_sellable: false,
    variant_id: null,
    thumbnail: "/images/test/project_thumbnail_1.jpg",
    theme_name: "dark",
    created_at: new Date("2024-10-08T17:00:00Z"),
    updated_at: new Date("2024-10-08T17:00:00Z"),
  },
  {
    id: "project_9",
    title: "Healthy Meal Plans",
    slides: null,
    user_id: "user_id_1",
    outlines: ["Breakfast", "Lunch", "Dinner", "Snacks"],
    is_deleted: false,
    is_sellable: true,
    variant_id: "variant_6",
    thumbnail: "/images/test/project_thumbnail_1.jpg",
    theme_name: "light",
    created_at: new Date("2024-10-09T18:00:00Z"),
    updated_at: new Date("2024-10-09T18:00:00Z"),
  },
  {
    id: "project_10",
    title: "DIY Home Repairs",
    slides: {
      slide1: "Tools",
      slide2: "Common Issues",
      slide3: "Step-by-Step Guides",
    },
    user_id: "user_id_1",
    outlines: ["Introduction", "Tools Needed", "Repair Guides", "Safety Tips"],
    is_deleted: false,
    is_sellable: true,
    variant_id: "variant_7",
    thumbnail: "/images/test/project_thumbnail_1.jpg",
    theme_name: "dark",
    created_at: new Date("2024-10-10T19:00:00Z"),
    updated_at: new Date("2024-10-10T19:00:00Z"),
  },
];

export const addProjects = async () => {
  await db.project.createMany({
    data: sample_data,
    skipDuplicates: true,
  });
};
